"""Initial database setup

Revision ID: 8db455685402
Revises: 
Create Date: 2025-12-30 13:31:37.105799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db455685402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_teams_week_number'), ['week_number'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_abbreviation'), ['abbreviation'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('favourite_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_favourite_teams_user_team')
    )
    with op.batch_alter_table('favourite_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_teams_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_teams_user_id'), ['user_id'], unique=False)

    op.create_table('matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_team_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('user_score', sa.Float(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=False),
    sa.Column('played_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_team_id'], ['ai_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ai_team_id', name='uq_matchups_user_ai_team')
    )
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matchups_ai_team_id'), ['ai_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchups_user_id'), ['user_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('height_weight', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('ai_team_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_team_id'], ['ai_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_team_id', 'player_id', name='uq_ai_team_players_ai_team_player')
    )
    with op.batch_alter_table('ai_team_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_team_players_ai_team_id'), ['ai_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_team_players_player_id'), ['player_id'], unique=False)

    op.create_table('favourite_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'player_id', name='uq_favourite_players_user_player')
    )
    with op.batch_alter_table('favourite_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_players_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_players_user_id'), ['user_id'], unique=False)

    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_stats_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_player_id'), ['player_id'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_team_id'), ['team_id'], unique=False)

    op.create_table('user_team_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'player_id', name='uq_user_team_players_user_player')
    )
    with op.batch_alter_table('user_team_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_team_players_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_team_players_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_team_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_team_players_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_team_players_player_id'))

    op.drop_table('user_team_players')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_team_id'))
        batch_op.drop_index(batch_op.f('ix_news_player_id'))

    op.drop_table('news')
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_game_date'))

    op.drop_table('game_stats')
    with op.batch_alter_table('favourite_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_players_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_players_player_id'))

    op.drop_table('favourite_players')
    with op.batch_alter_table('ai_team_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_team_players_player_id'))
        batch_op.drop_index(batch_op.f('ix_ai_team_players_ai_team_id'))

    op.drop_table('ai_team_players')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))

    op.drop_table('players')
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matchups_user_id'))
        batch_op.drop_index(batch_op.f('ix_matchups_ai_team_id'))

    op.drop_table('matchups')
    with op.batch_alter_table('favourite_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_teams_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_teams_team_id'))

    op.drop_table('favourite_teams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_abbreviation'))

    op.drop_table('teams')
    with op.batch_alter_table('ai_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_teams_week_number'))

    op.drop_table('ai_teams')
    # ### end Alembic commands ###
